import Head from "next/head";
import Image from "next/image";
import LeftSide from "../components/LeftSide";
import styles from "../styles/Home.module.css";
import Feed from "../components/Feed";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex ">
        {/* Left Side */}
        <LeftSide />
        {/* Middle */}
        <Feed />
        {/* Right Side */}
      </div>
    </div>
  );
}
