import Head from "next/head";
import Image from "next/image";
import LeftSide from "../components/LeftSide";
import styles from "../styles/Home.module.css";
import Feed from "../components/Feed";
import RightSide from "../components/RightSide";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Twitter Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/twitter.ico" />
      </Head>
      <div className="flex justify-center">
        {/* Left Side */}
        <LeftSide />
        {/* Middle */}
        <Feed />
        {/* Right Side */}
        <RightSide />
      </div>
    </div>
  );
}
